export interface SecurityTool {
  name: string;
  description: string;
  installCommand: Array<string>;
  usage: string;
  category: 'reconnaissance' | 'scanning' | 'exploitation' | 'analysis';
}

export const SECURITY_TOOLS: Array<SecurityTool> = [
  {
    name: 'nmap',
    description: 'Network exploration tool and security scanner',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'nmap'],
    usage: 'nmap -sV -sC <target>',
    category: 'scanning'
  },
  {
    name: 'masscan',
    description: 'Fast TCP port scanner',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'masscan'],
    usage: 'masscan -p1-65535 <target> --rate=1000',
    category: 'scanning'
  },
  {
    name: 'gobuster',
    description: 'Directory/file enumeration tool',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'gobuster'],
    usage: 'gobuster dir -u <target> -w /usr/share/wordlists/dirb/common.txt',
    category: 'reconnaissance'
  },
  {
    name: 'sqlmap',
    description: 'Automatic SQL injection tool',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'sqlmap'],
    usage: 'sqlmap -u "<target>" --batch --level=3',
    category: 'exploitation'
  },
  {
    name: 'nikto',
    description: 'Web vulnerability scanner',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'nikto'],
    usage: 'nikto -h <target>',
    category: 'scanning'
  },
  {
    name: 'nuclei',
    description: 'Vulnerability scanner with templates',
    installCommand: ['go', 'install', '-v', 'github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest'],
    usage: 'nuclei -u <target> -t /path/to/templates',
    category: 'scanning'
  },
  {
    name: 'subfinder',
    description: 'Subdomain discovery tool',
    installCommand: ['go', 'install', '-v', 'github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest'],
    usage: 'subfinder -d <domain>',
    category: 'reconnaissance'
  },
  {
    name: 'amass',
    description: 'Attack surface mapping tool',
    installCommand: ['go', 'install', '-v', 'github.com/OWASP/Amass/v3/...@master'],
    usage: 'amass enum -d <domain>',
    category: 'reconnaissance'
  },
  {
    name: 'httpx',
    description: 'HTTP toolkit for probing',
    installCommand: ['go', 'install', '-v', 'github.com/projectdiscovery/httpx/cmd/httpx@latest'],
    usage: 'httpx -l targets.txt -title -tech-detect',
    category: 'reconnaissance'
  },
  {
    name: 'ffuf',
    description: 'Fast web fuzzer',
    installCommand: ['go', 'install', 'github.com/ffuf/ffuf@latest'],
    usage: 'ffuf -w wordlist.txt -u <target>/FUZZ',
    category: 'reconnaissance'
  },
  {
    name: 'dirb',
    description: 'Web Content Scanner',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'dirb'],
    usage: 'dirb <target>',
    category: 'reconnaissance'
  },
  {
    name: 'wpscan',
    description: 'WordPress security scanner',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'wpscan'],
    usage: 'wpscan --url <wordpress-site> --enumerate u',
    category: 'scanning'
  },
  {
    name: 'whatweb',
    description: 'Web application fingerprinting',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'whatweb'],
    usage: 'whatweb <target>',
    category: 'reconnaissance'
  },
  {
    name: 'dig',
    description: 'DNS lookup tool',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'dnsutils'],
    usage: 'dig <domain> ANY',
    category: 'reconnaissance'
  },
  {
    name: 'curl',
    description: 'HTTP client for testing',
    installCommand: ['sudo', 'apt-get', 'install', '-y', 'curl'],
    usage: 'curl -I <target>',
    category: 'reconnaissance'
  }
];

export function getToolByName(name: string): SecurityTool | undefined {
  return SECURITY_TOOLS.find(tool => tool.name === name);
}

export function getToolsByCategory(category: SecurityTool['category']): Array<SecurityTool> {
  return SECURITY_TOOLS.filter(tool => tool.category === category);
}

export function generateToolInstallScript(tools: Array<string>): string {
  const selectedTools = tools.map(name => getToolByName(name)).filter(Boolean) as Array<SecurityTool>;
  
  let script = '#!/bin/bash\n\n';
  script += '# Bug Bounty Tools Installation Script\n';
  script += '# Generated by Codex Bounty Agent\n\n';
  script += 'set -e\n\n';
  script += 'echo "Installing security tools..."\n\n';
  
  // Update package lists
  script += 'sudo apt-get update\n\n';
  
  // Install tools
  selectedTools.forEach(tool => {
    script += `echo "Installing ${tool.name}..."\n`;
    script += `${tool.installCommand.join(' ')}\n\n`;
  });
  
  script += 'echo "All tools installed successfully!"\n';
  
  return script;
}

export function checkToolAvailability(toolName: string): Promise<boolean> {
  return new Promise((resolve) => {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { spawn } = require('child_process');
    const child = spawn('which', [toolName], { stdio: 'ignore' });
    
    child.on('close', (code: number) => {
      resolve(code === 0);
    });
    
    child.on('error', () => {
      resolve(false);
    });
  });
}